sources:
  - name: main
    tables:
      - name: raw_orders
        meta:
          dagster:
            asset_key: ["target", "data", "orders"]
      - name: raw_customers
        meta:
          dagster:
            asset_key: ["target", "data", "customers"]
      - name: raw_payments
        meta:
          dagster:
            asset_key: ["target", "data", "payments"]