sources:
  - name: main
    tables:
      - name: data_orders
        meta:
          dagster:
            asset_key: ["target", "data", "orders"]
      - name: data_customers
        meta:
          dagster:
            asset_key: ["target", "data", "customers"]
      - name: data_payments
        meta:
          dagster:
            asset_key: ["target", "data", "payments"]